#pragma once

#include <cstdint>

namespace bsp::eeprom {

/// @section Custom types

enum EepromResult {
    OK,
    ERROR,
    DATA_NOT_FOUND,
};

typedef enum : uint16_t {
    ADDR_MEMORY_CLEAR = 0x0000,

    // PARAMS 0x0004 ~ 0x0FFF
    ADDR_FAN_SPEED = 0x0004,
    ADDR_ANGULAR_KP = 0x0008,
    ADDR_ANGULAR_KI = 0x000C,
    ADDR_ANGULAR_KD = 0x0010,
    ADDR_WALL_KP = 0x0014,
    ADDR_WALL_KI = 0x0018,
    ADDR_WALL_KD = 0x001C,
    ADDR_LINEAR_VEL_KP = 0x0020,
    ADDR_LINEAR_VEL_KI = 0x0024,
    ADDR_LINEAR_VEL_KD = 0x0028,
    ADDR_DIAGONAL_WALLS_KP = 0x002C,
    ADDR_DIAGONAL_WALLS_KI = 0x0030,
    ADDR_DIAGONAL_WALLS_KD = 0x0034,
    ADDR_MIN_MOVE_SPEED = 0x0038,

    ADDR_IR_WALL_DIST_REF_LEFT = 0x003C,
    ADDR_IR_WALL_DIST_REF_RIGHT = 0x0040,
    ADDR_IR_WALL_DETECT_TH_LEFT = 0x0044,
    ADDR_IR_WALL_DETECT_TH_RIGHT = 0x0048,
    ADDR_IR_DIAGONAL_REF_FL = 0x004C,
    ADDR_IR_DIAGONAL_REF_FR = 0x0050,
    ADDR_IR_DIAGONAL_CONTROL_TH_FL = 0x0054,
    ADDR_IR_DIAGONAL_CONTROL_TH_FR = 0x0058,

    ADDR_SENSOR_R_SLOPE_MAX_TH = 0x005C,
    ADDR_SENSOR_L_SLOPE_MAX_TH = 0x0060,
    ADDR_RIGHT_SENSOR_ANGLE_DEG = 0x0064,
    ADDR_LEFT_SENSOR_ANGLE_DEG = 0x0068,
    ADDR_Z_IMU_BIAS = 0x006C,
    
    ADDR_START_WALL_BREAK_MM_LEFT = 0x0070,
    ADDR_START_WALL_BREAK_MM_RIGHT = 0x0074,
    ADDR_ENABLE_WALL_BREAK_CORRECTION = 0x0078,
    ADDR_ANGULAR_ACC_FEED_FORWARD_K = 0x007C,
    ADDR_ANGULAR_VEL_FEED_FORWARD_K = 0x0080,
    ADDR_LINEAR_VEL_ACC_FEED_FORWARD_K = 0x0084,
    ADDR_ANGULAR_BRAKE_FEED_FORWARD_K = 0x0088,
    ADDR_LINEAR_VEL_BRAKE_FEED_FORWARD_K = 0x008C,
    ADDR_LINEAR_VEL_FEED_FORWARD_K = 0x0090,
    ADDR_MAX_LINEAR_ACC_JERK = 0x0094,
    ADDR_MAX_LINEAR_BRAKE_JERK = 0x0098,
    ADDR_WHEEL_RADIUS_MM = 0x009C,
    ADDR_COULOMB_FF = 0x00A0,
    ADDR_ANGULAR_COULOMB_FF = 0x00A4,
    ADDR_ANGULAR_STATIC_FF = 0x00A8,
    ADDR_ENABLE_LATERAL_CORRECTION_90 = 0x00AC,
    ADDR_ENABLE_LATERAL_CORRECTION_WALL = 0x00B0,

    // IR CALIB PARAMS 0x1300 ~ 0x1330
    ADDR_IR_CALIB_A_RIGHT = 0x1300,
    ADDR_IR_CALIB_B_RIGHT = 0x1304,
    ADDR_IR_CALIB_C_RIGHT = 0x1308,
    ADDR_IR_CALIB_A_FRONT_LEFT = 0x130C,
    ADDR_IR_CALIB_B_FRONT_LEFT = 0x1310,
    ADDR_IR_CALIB_C_FRONT_LEFT = 0x1314,
    ADDR_IR_CALIB_A_FRONT_RIGHT = 0x1318,
    ADDR_IR_CALIB_B_FRONT_RIGHT = 0x131C,
    ADDR_IR_CALIB_C_FRONT_RIGHT = 0x1320,
    ADDR_IR_CALIB_A_LEFT = 0x1324,
    ADDR_IR_CALIB_B_LEFT = 0x1328,
    ADDR_IR_CALIB_C_LEFT = 0x132C,

    // IR WALL PATTERNS 0x1330 ~ 0x13B0
    ADDR_IR_WALL_PATTERNS_START = 0x1330,
    ADDR_IR_WALL_PATTERN_0_L = 0x1330,
    ADDR_IR_WALL_PATTERN_0_FL = 0x1334,
    ADDR_IR_WALL_PATTERN_0_FR = 0x1338,
    ADDR_IR_WALL_PATTERN_0_R = 0x133C,
    ADDR_IR_WALL_PATTERN_1_L = 0x1340,
    ADDR_IR_WALL_PATTERN_1_FL = 0x1344,
    ADDR_IR_WALL_PATTERN_1_FR = 0x1348,
    ADDR_IR_WALL_PATTERN_1_R = 0x134C,
    ADDR_IR_WALL_PATTERN_2_L = 0x1350,
    ADDR_IR_WALL_PATTERN_2_FL = 0x1354,
    ADDR_IR_WALL_PATTERN_2_FR = 0x1358,
    ADDR_IR_WALL_PATTERN_2_R = 0x135C,
    ADDR_IR_WALL_PATTERN_3_L = 0x1360,
    ADDR_IR_WALL_PATTERN_3_FL = 0x1364,
    ADDR_IR_WALL_PATTERN_3_FR = 0x1368,
    ADDR_IR_WALL_PATTERN_3_R = 0x136C,
    ADDR_IR_WALL_PATTERN_4_L = 0x1370,
    ADDR_IR_WALL_PATTERN_4_FL = 0x1374,
    ADDR_IR_WALL_PATTERN_4_FR = 0x1378,
    ADDR_IR_WALL_PATTERN_4_R = 0x137C,
    ADDR_IR_WALL_PATTERN_5_L = 0x1380,
    ADDR_IR_WALL_PATTERN_5_FL = 0x1384,
    ADDR_IR_WALL_PATTERN_5_FR = 0x1388,
    ADDR_IR_WALL_PATTERN_5_R = 0x138C,
    ADDR_IR_WALL_PATTERN_6_L = 0x1390,
    ADDR_IR_WALL_PATTERN_6_FL = 0x1394,
    ADDR_IR_WALL_PATTERN_6_FR = 0x1398,
    ADDR_IR_WALL_PATTERN_6_R = 0x139C,
    ADDR_IR_WALL_PATTERN_7_L = 0x13A0,
    ADDR_IR_WALL_PATTERN_7_FL = 0x13A4,
    ADDR_IR_WALL_PATTERN_7_FR = 0x13A8,
    ADDR_IR_WALL_PATTERN_7_R = 0x13AC,

    // FOWARD PARAMS 0x1400 ~ 0x1600
    ADDR_FORWARD_PARAMS_START = 0x1400,
    ADDR_FORWARD_PARAMS_FOWARD = 0x1410,
    ADDR_FORWARD_PARAMS_DIAGONAL = 0x1420,
    ADDR_FORWARD_PARAMS_STOP = 0x1430,
    ADDR_FORWARD_PARAMS_TURN_AROUND = 0x1440,
    ADDR_FORWARD_PARAMS_RIGHT_45_FROM_45 = 0x1450,
    ADDR_FORWARD_PARAMS_LEFT_45_FROM_45 = 0x1460,
    ADDR_FORWARD_PARAMS_RIGHT_90_FROM_45 = 0x1470,
    ADDR_FORWARD_PARAMS_LEFT_90_FROM_45 = 0x1480,
    ADDR_FORWARD_PARAMS_RIGHT_135_FROM_45 = 0x1490,
    ADDR_FORWARD_PARAMS_LEFT_135_FROM_45 = 0x14A0,
    ADDR_FORWARD_PARAMS_RIGHT_90_SEARCH = 0x14B0,
    ADDR_FORWARD_PARAMS_LEFT_90_SEARCH = 0x14C0,
    ADDR_FORWARD_PARAMS_TURN_AROUND_INPLACE = 0x14D0,
    ADDR_FORWARD_PARAMS_RIGHT_90 = 0x14E0,
    ADDR_FORWARD_PARAMS_LEFT_90 = 0x14F0,
    ADDR_FORWARD_PARAMS_RIGHT_45 = 0x1500,
    ADDR_FORWARD_PARAMS_LEFT_45 = 0x1510,
    ADDR_FORWARD_PARAMS_RIGHT_135 = 0x1520,
    ADDR_FORWARD_PARAMS_LEFT_135 = 0x1530,
    ADDR_FORWARD_PARAMS_RIGHT_180 = 0x1540,
    ADDR_FORWARD_PARAMS_LEFT_180 = 0x1550,

    // TURN PARAMS 0x1600 ~ 0x1960
    ADDR_TURN_PARAMS_RIGHT_45 = 0x1600,
    ADDR_TURN_PARAMS_LEFT_45 = 0x1630,
    ADDR_TURN_PARAMS_RIGHT_90 = 0x1660,
    ADDR_TURN_PARAMS_LEFT_90 = 0x1690,
    ADDR_TURN_PARAMS_RIGHT_135 = 0x16C0,
    ADDR_TURN_PARAMS_LEFT_135 = 0x16F0,
    ADDR_TURN_PARAMS_RIGHT_180 = 0x1720,
    ADDR_TURN_PARAMS_LEFT_180 = 0x1750,
    ADDR_TURN_PARAMS_RIGHT_45_FROM_45 = 0x1780,
    ADDR_TURN_PARAMS_LEFT_45_FROM_45 = 0x17B0,
    ADDR_TURN_PARAMS_RIGHT_90_FROM_45 = 0x17E0,
    ADDR_TURN_PARAMS_LEFT_90_FROM_45 = 0x1810,
    ADDR_TURN_PARAMS_RIGHT_135_FROM_45 = 0x1840,
    ADDR_TURN_PARAMS_LEFT_135_FROM_45 = 0x1870,
    ADDR_TURN_PARAMS_TURN_AROUND = 0x18A0,
    ADDR_TURN_PARAMS_RIGHT_90_SEARCH_MODE = 0x18D0,
    ADDR_TURN_PARAMS_LEFT_90_SEARCH_MODE = 0x1900,
    ADDR_TURN_PARAMS_TURN_AROUND_INPLACE = 0x1930,

    // MOVE SEQUENCE 0x2000 ~ 0x2100
    ADDR_MOVE_SEQUENCE_1 = 0x2000,
    ADDR_MOVE_SEQUENCE_2 = 0x2001,
    ADDR_MOVE_SEQUENCE_3 = 0x2002,
    ADDR_MOVE_SEQUENCE_4 = 0x2003,
    ADDR_MOVE_SEQUENCE_5 = 0x2004,
    ADDR_MOVE_SEQUENCE_6 = 0x2005,
    ADDR_MOVE_SEQUENCE_7 = 0x2006,
    ADDR_MOVE_SEQUENCE_8 = 0x2007,
    ADDR_MOVE_SEQUENCE_9 = 0x2008,
    ADDR_MOVE_SEQUENCE_10 = 0x2009,
    ADDR_MOVE_SEQUENCE_11 = 0x200A,
    ADDR_MOVE_SEQUENCE_12 = 0x200B,
    ADDR_MOVE_SEQUENCE_13 = 0x200C,
    ADDR_MOVE_SEQUENCE_14 = 0x200D,
    ADDR_MOVE_SEQUENCE_15 = 0x200E,
    ADDR_MOVE_SEQUENCE_16 = 0x200F,
    ADDR_MOVE_SEQUENCE_17 = 0x2010,
    ADDR_MOVE_SEQUENCE_18 = 0x2011,

    // MAZE 0x3000 ~ 0x4000
    ADDR_MAZE_START = 0x3000,

    // MAZE_BACKUP 0x4000 ~ 0x5000
    ADDR_MAZE_BACKUP_START = 0x4000,

    ADDR_MAX = 0xFFFF,
} param_addresses_t;

struct ParamInfo {
    uint16_t address;
    const char* name;
};

// Initialize the array with address-name pairs
const ParamInfo paramInfoArray[] = {
    {ADDR_MEMORY_CLEAR, "ADDR_MEMORY_CLEAR"},
    {ADDR_FAN_SPEED, "ADDR_FAN_SPEED"},
    {ADDR_ANGULAR_KP, "ADDR_ANGULAR_KP"},
    {ADDR_ANGULAR_KI, "ADDR_ANGULAR_KI"},
    {ADDR_ANGULAR_KD, "ADDR_ANGULAR_KD"},
    {ADDR_WALL_KP, "ADDR_WALL_KP"},
    {ADDR_WALL_KI, "ADDR_WALL_KI"},
    {ADDR_WALL_KD, "ADDR_WALL_KD"},
    {ADDR_LINEAR_VEL_KP, "ADDR_LINEAR_VEL_KP"},
    {ADDR_LINEAR_VEL_KI, "ADDR_LINEAR_VEL_KI"},
    {ADDR_LINEAR_VEL_KD, "ADDR_LINEAR_VEL_KD"},
    {ADDR_DIAGONAL_WALLS_KP, "ADDR_DIAGONAL_WALLS_KP"},
    {ADDR_DIAGONAL_WALLS_KI, "ADDR_DIAGONAL_WALLS_KI"},
    {ADDR_DIAGONAL_WALLS_KD, "ADDR_DIAGONAL_WALLS_KD"},
    {ADDR_MIN_MOVE_SPEED, "ADDR_MIN_MOVE_SPEED"},
    {ADDR_IR_WALL_DIST_REF_LEFT, "ADDR_IR_WALL_DIST_REF_LEFT"},
    {ADDR_IR_WALL_DIST_REF_RIGHT, "ADDR_IR_WALL_DIST_REF_RIGHT"},
    {ADDR_IR_WALL_DETECT_TH_LEFT, "ADDR_IR_WALL_DETECT_TH_LEFT"},
    {ADDR_IR_WALL_DETECT_TH_RIGHT, "ADDR_IR_WALL_DETECT_TH_RIGHT"},
    {ADDR_IR_DIAGONAL_REF_FL, "ADDR_IR_DIAGONAL_REF_FL"},
    {ADDR_IR_DIAGONAL_REF_FR, "ADDR_IR_DIAGONAL_REF_FR"},
    {ADDR_IR_DIAGONAL_CONTROL_TH_FL, "ADDR_IR_DIAGONAL_CONTROL_TH_FL"},
    {ADDR_IR_DIAGONAL_CONTROL_TH_FR, "ADDR_IR_DIAGONAL_CONTROL_TH_FR"},
    {ADDR_Z_IMU_BIAS, "ADDR_Z_IMU_BIAS"},
    {ADDR_SENSOR_R_SLOPE_MAX_TH, "ADDR_SENSOR_R_SLOPE_MAX_TH"},
    {ADDR_SENSOR_L_SLOPE_MAX_TH, "ADDR_SENSOR_L_SLOPE_MAX_TH"},
    {ADDR_RIGHT_SENSOR_ANGLE_DEG, "ADDR_RIGHT_SENSOR_ANGLE_DEG"},
    {ADDR_LEFT_SENSOR_ANGLE_DEG, "ADDR_LEFT_SENSOR_ANGLE_DEG"},
    {ADDR_START_WALL_BREAK_MM_LEFT, "ADDR_START_WALL_BREAK_MM_LEFT"},
    {ADDR_START_WALL_BREAK_MM_RIGHT, "ADDR_START_WALL_BREAK_MM_RIGHT"},
    {ADDR_ENABLE_WALL_BREAK_CORRECTION, "ADDR_ENABLE_WALL_BREAK_CORRECTION"},
    {ADDR_ANGULAR_ACC_FEED_FORWARD_K, "ADDR_ANGULAR_ACC_FEED_FORWARD_K"},
    {ADDR_ANGULAR_VEL_FEED_FORWARD_K, "ADDR_ANGULAR_VEL_FEED_FORWARD_K"},
    {ADDR_LINEAR_VEL_ACC_FEED_FORWARD_K, "ADDR_LINEAR_VEL_ACC_FEED_FORWARD_K"},
    {ADDR_ANGULAR_BRAKE_FEED_FORWARD_K, "ADDR_ANGULAR_BRAKE_FEED_FORWARD_K"},
    {ADDR_LINEAR_VEL_BRAKE_FEED_FORWARD_K, "ADDR_LINEAR_VEL_BRAKE_FEED_FORWARD_K"},
    {ADDR_LINEAR_VEL_FEED_FORWARD_K, "ADDR_LINEAR_VEL_FEED_FORWARD_K"},
    {ADDR_MAX_LINEAR_ACC_JERK, "ADDR_MAX_LINEAR_ACC_JERK"},
    {ADDR_MAX_LINEAR_BRAKE_JERK, "ADDR_MAX_LINEAR_BRAKE_JERK"},
    {ADDR_WHEEL_RADIUS_MM, "ADDR_WHEEL_RADIUS_MM"},
    {ADDR_COULOMB_FF, "ADDR_COULOMB_FF"},
    {ADDR_ANGULAR_COULOMB_FF, "ADDR_ANGULAR_COULOMB_FF"},
    {ADDR_ANGULAR_STATIC_FF, "ADDR_ANGULAR_STATIC_FF"},
    {ADDR_ENABLE_LATERAL_CORRECTION_90, "ADDR_ENABLE_LATERAL_CORRECTION_90"},
    {ADDR_ENABLE_LATERAL_CORRECTION_WALL, "ADDR_ENABLE_LATERAL_CORRECTION_WALL"},
    {ADDR_IR_CALIB_A_RIGHT, "ADDR_IR_CALIB_A_RIGHT"},
    {ADDR_IR_CALIB_B_RIGHT, "ADDR_IR_CALIB_B_RIGHT"},
    {ADDR_IR_CALIB_C_RIGHT, "ADDR_IR_CALIB_C_RIGHT"},
    {ADDR_IR_CALIB_A_FRONT_LEFT, "ADDR_IR_CALIB_A_FRONT_LEFT"},
    {ADDR_IR_CALIB_B_FRONT_LEFT, "ADDR_IR_CALIB_B_FRONT_LEFT"},
    {ADDR_IR_CALIB_C_FRONT_LEFT, "ADDR_IR_CALIB_C_FRONT_LEFT"},
    {ADDR_IR_CALIB_A_FRONT_RIGHT, "ADDR_IR_CALIB_A_FRONT_RIGHT"},
    {ADDR_IR_CALIB_B_FRONT_RIGHT, "ADDR_IR_CALIB_B_FRONT_RIGHT"},
    {ADDR_IR_CALIB_C_FRONT_RIGHT, "ADDR_IR_CALIB_C_FRONT_RIGHT"},
    {ADDR_IR_CALIB_A_LEFT, "ADDR_IR_CALIB_A_LEFT"},
    {ADDR_IR_CALIB_B_LEFT, "ADDR_IR_CALIB_B_LEFT"},
    {ADDR_IR_CALIB_C_LEFT, "ADDR_IR_CALIB_C_LEFT"},
    {ADDR_IR_WALL_PATTERN_0_L, "ADDR_IR_WALL_PATTERN_0_L"},
    {ADDR_IR_WALL_PATTERN_0_FL, "ADDR_IR_WALL_PATTERN_0_FL"},
    {ADDR_IR_WALL_PATTERN_0_FR, "ADDR_IR_WALL_PATTERN_0_FR"},
    {ADDR_IR_WALL_PATTERN_0_R, "ADDR_IR_WALL_PATTERN_0_R"},
    {ADDR_IR_WALL_PATTERN_1_L, "ADDR_IR_WALL_PATTERN_1_L"},
    {ADDR_IR_WALL_PATTERN_1_FL, "ADDR_IR_WALL_PATTERN_1_FL"},
    {ADDR_IR_WALL_PATTERN_1_FR, "ADDR_IR_WALL_PATTERN_1_FR"},
    {ADDR_IR_WALL_PATTERN_1_R, "ADDR_IR_WALL_PATTERN_1_R"},
    {ADDR_IR_WALL_PATTERN_2_L, "ADDR_IR_WALL_PATTERN_2_L"},
    {ADDR_IR_WALL_PATTERN_2_FL, "ADDR_IR_WALL_PATTERN_2_FL"},
    {ADDR_IR_WALL_PATTERN_2_FR, "ADDR_IR_WALL_PATTERN_2_FR"},
    {ADDR_IR_WALL_PATTERN_2_R, "ADDR_IR_WALL_PATTERN_2_R"},
    {ADDR_IR_WALL_PATTERN_3_L, "ADDR_IR_WALL_PATTERN_3_L"},
    {ADDR_IR_WALL_PATTERN_3_FL, "ADDR_IR_WALL_PATTERN_3_FL"},
    {ADDR_IR_WALL_PATTERN_3_FR, "ADDR_IR_WALL_PATTERN_3_FR"},
    {ADDR_IR_WALL_PATTERN_3_R, "ADDR_IR_WALL_PATTERN_3_R"},
    {ADDR_IR_WALL_PATTERN_4_L, "ADDR_IR_WALL_PATTERN_4_L"},
    {ADDR_IR_WALL_PATTERN_4_FL, "ADDR_IR_WALL_PATTERN_4_FL"},
    {ADDR_IR_WALL_PATTERN_4_FR, "ADDR_IR_WALL_PATTERN_4_FR"},
    {ADDR_IR_WALL_PATTERN_4_R, "ADDR_IR_WALL_PATTERN_4_R"},
    {ADDR_IR_WALL_PATTERN_5_L, "ADDR_IR_WALL_PATTERN_5_L"},
    {ADDR_IR_WALL_PATTERN_5_FL, "ADDR_IR_WALL_PATTERN_5_FL"},
    {ADDR_IR_WALL_PATTERN_5_FR, "ADDR_IR_WALL_PATTERN_5_FR"},
    {ADDR_IR_WALL_PATTERN_5_R, "ADDR_IR_WALL_PATTERN_5_R"},
    {ADDR_IR_WALL_PATTERN_6_L, "ADDR_IR_WALL_PATTERN_6_L"},
    {ADDR_IR_WALL_PATTERN_6_FL, "ADDR_IR_WALL_PATTERN_6_FL"},
    {ADDR_IR_WALL_PATTERN_6_FR, "ADDR_IR_WALL_PATTERN_6_FR"},
    {ADDR_IR_WALL_PATTERN_6_R, "ADDR_IR_WALL_PATTERN_6_R"},
    {ADDR_IR_WALL_PATTERN_7_L, "ADDR_IR_WALL_PATTERN_7_L"},
    {ADDR_IR_WALL_PATTERN_7_FL, "ADDR_IR_WALL_PATTERN_7_FL"},
    {ADDR_IR_WALL_PATTERN_7_FR, "ADDR_IR_WALL_PATTERN_7_FR"},
    {ADDR_IR_WALL_PATTERN_7_R, "ADDR_IR_WALL_PATTERN_7_R"}
};

/// @section Interface definition

EepromResult init(void);

EepromResult read_u8(uint16_t address, uint8_t* data);
EepromResult write_u8(uint16_t address, uint8_t data);
EepromResult read_u16(uint16_t address, uint16_t* data);
EepromResult write_u16(uint16_t address, uint16_t data);
EepromResult read_u32(uint16_t address, uint32_t* data);
EepromResult read_array(uint16_t address, uint8_t* data, uint16_t size);
EepromResult write_u32(uint16_t address, uint32_t data);
EepromResult write_array(uint16_t address, uint8_t* data, uint16_t size);

void clear(void);
void print_all(void);
const char* param_name(uint16_t address);

}
